// Autogenerated from Pigeon (v0.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class HJPhotoPickerResult;
@class HJPhotoPickerOptions;

@interface HJPhotoPickerResult : NSObject
@property(nonatomic, strong, nullable) NSArray * assets;
@end

@interface HJPhotoAsset : NSObject
@property(nonatomic, copy, nullable) NSString *filePath;
@end

@interface HJPhotoPickerOptions : NSObject
@property(nonatomic, strong, nullable) NSNumber * type;
@property(nonatomic, strong, nullable) NSNumber * maxAssetsCount;
@property(nonatomic, strong, nullable) NSNumber * allowEdit;
@property(nonatomic, strong, nullable) NSNumber * videoMaximumDuration;
@property(nonatomic, strong, nullable) NSNumber * videoMinimumDuration;
@property(nonatomic, strong, nullable) NSNumber * singleJumpEdit;
@property(nonatomic, strong, nullable) NSNumber * isRoundCliping;
@property(nonatomic, strong, nullable) NSNumber * reverseDate;
@end

@protocol HJPhotoPicker
-(void)pickPhoto:(nullable HJPhotoPickerOptions *)input completion:(void(^)(HJPhotoPickerResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void HJPhotoPickerSetup(id<FlutterBinaryMessenger> binaryMessenger, id<HJPhotoPicker> _Nullable api);

NS_ASSUME_NONNULL_END
